DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS picture;
DROP TABLE IF EXISTS metadata;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE picture (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  path TEXT NOT NULL,
  FOREIGN KEY (author_id) REFERENCES user (id)
);

CREATE TABLE metadata (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  picture_id INTEGER NOT NULL,
  date TEXT NOT NULL,
  brightness TEXT NOT NULL,
  speed TEXT NOT NULL,
  zoom TEXT NOT NULL,
  aperture TEXT NOT NULL,
  FOREIGN KEY (picture_id) REFERENCES picture (id)
);
